# Generated by Django 3.1.7 on 2021-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstore',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
