# Generated by Django 3.1.7 on 2021-03-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_v2', '0003_auto_20210317_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='photo_profile',
            field=models.ImageField(default='0', upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='tbldocuments',
            name='photo',
            field=models.ImageField(upload_to='images/store/'),
        ),
    ]
