# Generated by Django 3.1.7 on 2021-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in_v2', '0005_auto_20210318_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitem',
            name='id_desc',
        ),
        migrations.AddField(
            model_name='tblitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tblitem',
            name='photo_item',
            field=models.ImageField(default='0', upload_to='images/item/'),
        ),
        migrations.AddField(
            model_name='tblitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TblDescItem',
        ),
    ]
